### PR TITLE
Version 0.6.11

### PR DESCRIPTION
**Pull request by ip1981**
@ezyang would you mind making a release?

As Github does not allow private messages, I'm writing with a payload :D

### CODE REVIEW

**Comment by ezyang** [comment]
Hi @ip1981, what is your Hackage username? I'll add you to the maintainers group.

**Comment by ip1981** [comment]
ip1981 :)

**Comment by ip1981** [comment]
Ok to merge this?

**Comment by ezyang** [comment]
Yep. Did you get Hackage bits? The web interface didn't seem to update when I put you in.

**Comment by ip1981** [comment]
I see "Maintainers for LDAP" at http://hackage.haskell.org/user/ip1981. If you mean LDAP page itself, I guess it only shows who is in the cabal file.

**Comment by ip1981** [comment]
http://hackage.haskell.org/package/LDAP-0.6.11

**Pull request merged**
