### PR TITLE
Add the ldapExternalSaslBind function for trivial (no control, no interaction) external SASL binds

### PR DESCRIPTION
**Pull request by wferi**
Hi,
I'm starting to use this functionality, would you please consider including it? This could be done in a more general fashion, but that's out of my scope right now.

### CODE REVIEW

**Comment by ip1981** [comment]
Yes, please.

**Comment by ip1981** [comment]
I want it for local maintenance tasks, which I prefer to do with a dedicated user and unix socket auth.

**Comment by ip1981** [comment]
https://github.com/ip1981/ldapply ;-) Please, please, please

**Comment by ezyang** [comment]
@ip1981 and @wferi I added both of you as collaborators to the repo!

**Comment by ip1981** [comment]
So, nobody minds merging this? (It works).

**Comment by wferi** [comment]
Three questions to consider:

- Should `sasl_trivial_external` be _safe_ as well (see 50f5be1d06bd47df9fe000d4b173b406b2e526b4)?
- Shouldn't we reserve the `ldapExternalSaslBind` name for a more generic (future) function, which allows specifying LDAP controls and a nontrivial interaction callback?
- Why did I call `ldap_sasl_interactive_bind_s()` instead of `ldap_sasl_bind_s()` in the first place? The latter looks considerably simpler to use, and unfortunately I don't remember...

**Comment by ezyang** [comment]
Mostly docs would be appreciated!

**Comment by ip1981** [comment]
Actually, anything that allows access sasl bind will be good.

**Comment by ip1981** [comment]
For `ldap_sasl_interactive_bind_s()`:

> Many SASL mechanisms require multiple message exchanges to perform a complete authentication. Applications should generally use ldap_sasl_interactive_bind_s() rather than calling the basic ldap_sasl_bind() functions directly.

I'd call it `ldapSimpleExternalBind`.

**Pull request closed without merging**
